version: '3'

services:
  heroes-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heroes-app
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heroes-app.rule=Host(`riu-frontend-challenge.agustin-goni.com`)"
      - "traefik.http.routers.heroes-app.entrypoints=websecure"
      - "traefik.http.routers.heroes-app.tls.certresolver=myresolver"
      - "traefik.http.services.heroes-app.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true